INSERT INTO Ingredients VALUES (1, 'Steak', 'Beef');
INSERT INTO Ingredients VALUES (2, 'Black Pepper', 'Spice');
INSERT INTO Ingredients VALUES (3, 'Salt', null);
INSERT INTO Ingredients VALUES (4, 'Rosemary', 'Herb');
INSERT INTO Ingredients VALUES (5, 'Butter', 'Dairy');
INSERT INTO Ingredients VALUES (6, 'Bread', null);
INSERT INTO Ingredients VALUES (7, 'Mayonnaise', 'Condiment');
INSERT INTO Ingredients VALUES (8, 'Bacon', 'Pork');
INSERT INTO Ingredients VALUES (9, 'Lettuce', 'Vegetable');
INSERT INTO Ingredients VALUES (10, 'Tomato', 'Vegetable');
INSERT INTO Ingredients VALUES (11, 'Turkey', 'Poultry');
INSERT INTO Ingredients VALUES (12, 'Paprika', 'Spice');
INSERT INTO Ingredients VALUES (13, 'Egg', 'Poultry');
INSERT INTO Ingredients VALUES (14, 'Chicken', 'Poultry');
INSERT INTO Ingredients VALUES (15, 'Onion', 'Vegetable');
INSERT INTO Ingredients VALUES (16, 'Tortilla', null);
INSERT INTO Ingredients VALUES (17, 'Lime', 'Fruit');
INSERT INTO Ingredients VALUES (18, 'Cilantro', 'Herb');
INSERT INTO Ingredients VALUES (19, 'Romaine Lettuce', 'Vegetable');
INSERT INTO Ingredients VALUES (20, 'Parmesan Cheese', 'Dairy');
INSERT INTO Ingredients VALUES (21, 'Crouton', null);
INSERT INTO Ingredients VALUES (22, 'Ranch Dressing', null);
INSERT INTO Ingredients VALUES (23, 'Snail', null);
INSERT INTO Ingredients VALUES (24, 'Chickpeas', 'Bean');
INSERT INTO Ingredients VALUES (25, 'Tahini', null);
INSERT INTO Ingredients VALUES (26, 'Lemon Juice', null);
INSERT INTO Ingredients VALUES (27, 'Olive Oil', null);
INSERT INTO Ingredients VALUES (28, 'Garlic', null);
INSERT INTO Recipe VALUES (1, 'Flat Iron Steak', 'American', 0, 0);
INSERT INTO Recipe VALUES (2, 'BLT', 'American', 0, 0);
INSERT INTO Recipe VALUES (3, 'Turkey Sandwich', 'American', 0, 0);
INSERT INTO Recipe VALUES (4, 'Deviled Eggs', 'Italian', 0, 0);
INSERT INTO Recipe VALUES (5, 'Hard Boiled Eggs', 'Italian', 0, 0);
INSERT INTO Recipe VALUES (6, 'Scrambled Eggs', 'American', 0, 0);
INSERT INTO Recipe VALUES (7, 'Pollo Street Tacos', 'Mexican', 0, 0);
INSERT INTO Recipe VALUES (8, 'Chicken Caesar Salad', 'Mexican', 0, 0);
INSERT INTO Recipe VALUES (9, 'Escargot', 'French', 0, 0);
INSERT INTO Recipe VALUES (10, 'Hummus', 'Greek', 0, 0);
INSERT INTO RecIngredients VALUES (1, 1, 1.0, 'units');
INSERT INTO RecIngredients VALUES (1, 2, 1.0, 'units');
INSERT INTO RecIngredients VALUES (1, 3, 1.0, 'units');
INSERT INTO RecIngredients VALUES (1, 4, 1.0, 'units');
INSERT INTO RecIngredients VALUES (1, 5, 1.0, 'units');
INSERT INTO RecIngredients VALUES (2, 6, 1.0, 'units');
INSERT INTO RecIngredients VALUES (2, 7, 1.0, 'units');
INSERT INTO RecIngredients VALUES (2, 8, 1.0, 'units');
INSERT INTO RecIngredients VALUES (2, 9, 1.0, 'units');
INSERT INTO RecIngredients VALUES (2, 10, 1.0, 'units');
INSERT INTO RecIngredients VALUES (3, 6, 1.0, 'units');
INSERT INTO RecIngredients VALUES (3, 7, 1.0, 'units');
INSERT INTO RecIngredients VALUES (3, 9, 1.0, 'units');
INSERT INTO RecIngredients VALUES (3, 10, 1.0, 'units');
INSERT INTO RecIngredients VALUES (3, 11, 1.0, 'units');
INSERT INTO RecIngredients VALUES (4, 12, 1.0, 'units');
INSERT INTO RecIngredients VALUES (4, 13, 1.0, 'units');
INSERT INTO RecIngredients VALUES (4, 7, 1.0, 'units');
INSERT INTO RecIngredients VALUES (4, 3, 1.0, 'units');
INSERT INTO RecIngredients VALUES (4, 2, 1.0, 'units');
INSERT INTO RecIngredients VALUES (5, 13, 1.0, 'units');
INSERT INTO RecIngredients VALUES (5, 3, 1.0, 'units');
INSERT INTO RecIngredients VALUES (6, 13, 1.0, 'units');
INSERT INTO RecIngredients VALUES (6, 3, 1.0, 'units');
INSERT INTO RecIngredients VALUES (6, 5, 1.0, 'units');
INSERT INTO RecIngredients VALUES (7, 14, 1.0, 'units');
INSERT INTO RecIngredients VALUES (7, 15, 1.0, 'units');
INSERT INTO RecIngredients VALUES (7, 16, 1.0, 'units');
INSERT INTO RecIngredients VALUES (7, 17, 1.0, 'units');
INSERT INTO RecIngredients VALUES (7, 18, 1.0, 'units');
INSERT INTO RecIngredients VALUES (8, 14, 1.0, 'units');
INSERT INTO RecIngredients VALUES (8, 19, 1.0, 'units');
INSERT INTO RecIngredients VALUES (8, 20, 1.0, 'units');
INSERT INTO RecIngredients VALUES (8, 21, 1.0, 'units');
INSERT INTO RecIngredients VALUES (8, 22, 1.0, 'units');
INSERT INTO RecIngredients VALUES (8, 2, 1.0, 'units');
INSERT INTO RecIngredients VALUES (9, 5, 1.0, 'units');
INSERT INTO RecIngredients VALUES (9, 3, 1.0, 'units');
INSERT INTO RecIngredients VALUES (9, 23, 1.0, 'units');
INSERT INTO RecIngredients VALUES (10, 24, 1.0, 'units');
INSERT INTO RecIngredients VALUES (10, 25, 1.0, 'units');
INSERT INTO RecIngredients VALUES (10, 26, 1.0, 'units');
INSERT INTO RecIngredients VALUES (10, 27, 1.0, 'units');
INSERT INTO RecIngredients VALUES (10, 28, 1.0, 'units');
INSERT INTO RecIngredients VALUES (10, 3, 1.0, 'units');
