INSERT INTO Ingredients VALUES (1, 'Steak', null);
INSERT INTO Ingredients VALUES (2, 'Black Pepper', null);
INSERT INTO Ingredients VALUES (3, 'Salt', null);
INSERT INTO Ingredients VALUES (4, 'Rosemary', null);
INSERT INTO Ingredients VALUES (5, 'Butter', null);
INSERT INTO Ingredients VALUES (6, 'Bread', null);
INSERT INTO Ingredients VALUES (7, 'Mayonnaise', null);
INSERT INTO Ingredients VALUES (8, 'Bacon', null);
INSERT INTO Ingredients VALUES (9, 'Lettuce', null);
INSERT INTO Ingredients VALUES (10, 'Tomato', null);
INSERT INTO Ingredients VALUES (11, 'Turkey', null);
INSERT INTO Ingredients VALUES (12, 'Paprika', null);
INSERT INTO Ingredients VALUES (13, 'Egg', null);
INSERT INTO Ingredients VALUES (14, 'Chicken', null);
INSERT INTO Ingredients VALUES (15, 'Onion', null);
INSERT INTO Ingredients VALUES (16, 'Tortilla', null);
INSERT INTO Ingredients VALUES (17, 'Lime', null);
INSERT INTO Ingredients VALUES (18, 'Cilantro', null);
INSERT INTO Ingredients VALUES (19, 'Romaine Lettuce', null);
INSERT INTO Ingredients VALUES (20, 'Parmesan Cheese', null);
INSERT INTO Ingredients VALUES (21, 'Crouton', null);
INSERT INTO Ingredients VALUES (22, 'Ranch Dressing', null);
INSERT INTO Ingredients VALUES (23, 'Snail', null);
INSERT INTO Ingredients VALUES (24, 'Chickpeas', null);
INSERT INTO Ingredients VALUES (25, 'Tahini', null);
INSERT INTO Ingredients VALUES (26, 'Lemon Juice', null);
INSERT INTO Ingredients VALUES (27, 'Olive Oil', null);
INSERT INTO Ingredients VALUES (28, 'Garlic', null);
INSERT INTO Recipe VALUES (1, 'Flat Iron Steak', 'American', 0, 0);
INSERT INTO Recipe VALUES (2, 'BLT', 'American', 0, 0);
INSERT INTO Recipe VALUES (3, 'Turkey Sandwich', 'American', 0, 0);
INSERT INTO Recipe VALUES (4, 'Deviled Eggs', 'Italian', 0, 0);
INSERT INTO Recipe VALUES (5, 'Hard Boiled Eggs', 'Italian', 0, 0);
INSERT INTO Recipe VALUES (6, 'Scrambled Eggs', 'American', 0, 0);
INSERT INTO Recipe VALUES (7, 'Pollo Street Tacos', 'Mexican', 0, 0);
INSERT INTO Recipe VALUES (8, 'Chicken Caesar Salad', 'Mexican', 0, 0);
INSERT INTO Recipe VALUES (9, 'Escargot', 'French', 0, 0);
INSERT INTO Recipe VALUES (10, 'Hummus', 'Greek', 0, 0);
INSERT INTO RecIngredients VALUES (1, 1);
INSERT INTO RecIngredients VALUES (1, 2);
INSERT INTO RecIngredients VALUES (1, 3);
INSERT INTO RecIngredients VALUES (1, 4);
INSERT INTO RecIngredients VALUES (1, 5);
INSERT INTO RecIngredients VALUES (2, 6);
INSERT INTO RecIngredients VALUES (2, 7);
INSERT INTO RecIngredients VALUES (2, 8);
INSERT INTO RecIngredients VALUES (2, 9);
INSERT INTO RecIngredients VALUES (2, 10);
INSERT INTO RecIngredients VALUES (3, 6);
INSERT INTO RecIngredients VALUES (3, 7);
INSERT INTO RecIngredients VALUES (3, 9);
INSERT INTO RecIngredients VALUES (3, 10);
INSERT INTO RecIngredients VALUES (3, 11);
INSERT INTO RecIngredients VALUES (4, 12);
INSERT INTO RecIngredients VALUES (4, 13);
INSERT INTO RecIngredients VALUES (4, 7);
INSERT INTO RecIngredients VALUES (4, 3);
INSERT INTO RecIngredients VALUES (4, 2);
INSERT INTO RecIngredients VALUES (5, 13);
INSERT INTO RecIngredients VALUES (5, 3);
INSERT INTO RecIngredients VALUES (6, 13);
INSERT INTO RecIngredients VALUES (6, 3);
INSERT INTO RecIngredients VALUES (6, 5);
INSERT INTO RecIngredients VALUES (7, 14);
INSERT INTO RecIngredients VALUES (7, 15);
INSERT INTO RecIngredients VALUES (7, 16);
INSERT INTO RecIngredients VALUES (7, 17);
INSERT INTO RecIngredients VALUES (7, 18);
INSERT INTO RecIngredients VALUES (8, 14);
INSERT INTO RecIngredients VALUES (8, 19);
INSERT INTO RecIngredients VALUES (8, 20);
INSERT INTO RecIngredients VALUES (8, 21);
INSERT INTO RecIngredients VALUES (8, 22);
INSERT INTO RecIngredients VALUES (8, 2);
INSERT INTO RecIngredients VALUES (9, 5);
INSERT INTO RecIngredients VALUES (9, 3);
INSERT INTO RecIngredients VALUES (9, 23);
INSERT INTO RecIngredients VALUES (10, 24);
INSERT INTO RecIngredients VALUES (10, 25);
INSERT INTO RecIngredients VALUES (10, 26);
INSERT INTO RecIngredients VALUES (10, 27);
INSERT INTO RecIngredients VALUES (10, 28);
INSERT INTO RecIngredients VALUES (10, 3);
